[package]

name = "img_hash"
version = "2.0.1"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A simple library that provides perceptual hashing and difference calculation for images."

license = "MIT OR Apache-2.0"

documentation = "http://docs.rs/img_hash"

keywords = ["image", "hash", "perceptual", "difference"]

repository = "http://github.com/abonander/img_hash"

[features]
default = ["rust-image"]
rust-image = ["image"]
bench = []

[dependencies]
bit-vec = "0.4"
rustc-serialize = "0.3"

[dependencies.img_hash_derives]
# git = "https://github.com/abonander/img_hash"
path = "img_hash_derives/"

[dev-dependencies]
rand = "0.3"
image = ">=0.10, <=0.13"

[dependencies.image]
version = ">=0.10, <=0.13"
optional = true

[profile.release]
debug = true
