[package]

name = "img_hash"
version = "2.0.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A simple library that provides perceptual hashing and difference calculation for images."

license = "MIT"

documentation = "http://rust-ci.org/cybergeek94/img_hash/doc/img_hash/"

keywords = ["image", "hash", "perceptual", "difference"]

repository = "http://github.com/cybergeek94/img_hash"

[features]
rust-image = ["image"]
bench = []

[dependencies]
bit-vec = "*"
rustc-serialize = "*"

[dev-dependencies]
rand = "*"
image = "*"

[dependencies.image]
version = "*"
optional = true

