[package]

name = "img_hash"
version = "0.0.3"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A simple library that provides perceptual hashing and difference calculation for images."

license = "MIT"

documentation = "http://rust-ci.org/cybergeek94/img_hash/doc/img_hash/"

keywords = ["image", "hash", "perceptual", "difference"]

repository = "http://github.com/cybergeek94/img_hash"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image.git"

